from sentence_transformers import SentenceTransformer


class EmbeddingService:
    """
    Creates embeddings for document chunks and user queries.

    The embedding dimension is read directly from the selected model
    instead of being hardcoded.
    """

    def __init__(self):
        self.model = SentenceTransformer(
            "sentence-transformers/all-MiniLM-L6-v2"
        )

    def get_dimension(self) -> int:
        """
        Returns the embedding size generated by the loaded model.
        """

        dimension = self.model.get_sentence_embedding_dimension()

        if dimension is None:
            raise ValueError(
                "Could not determine the embedding model dimension."
            )

        return dimension

    def create_embeddings(self, chunks: list[dict]) -> list[dict]:
        if not chunks:
            return []

        texts = [chunk["content"] for chunk in chunks]

        vectors = self.model.encode(
            texts,
            convert_to_numpy=True,
        )

        return [
            {
                "chunk_id": chunk["chunk_id"],
                "content": chunk["content"],
                "embedding": vector,
            }
            for chunk, vector in zip(chunks, vectors)
        ]

    def embed_query(self, query: str):
        return self.model.encode(
            [query],
            convert_to_numpy=True,
        )[0]